openapi: 3.0.1
info:
  title: dev-investor-portal-api
  description: Api for Investor access methods
  contact:
    name: Tony DiTomasso
    email: tony@avgfunds.com
  version: 1.2.3
servers:
- url: "https://e56bxipr3d.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: dev
tags:
- name: User Methods
  description: Services to access and create users
paths:
  /api/user-investments:
    get:
      operationId: apiUser_investmentsGET
      parameters:
      - name: custom-header
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      security:
      - auth: []
      x-swagger-router-controller: Default
    options:
      operationId: apiUser_investmentsOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
  /api/login:
    post:
      tags:
      - User Methods
      summary: Login
      description: Login investor user
      operationId: apiLoginPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
      x-swagger-router-controller: UserMethods
  /api/fund-investments:
    get:
      operationId: apiFund_investmentsGET
      parameters:
      - name: custom-header
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: fund-code
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: base-fund-code
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      security:
      - auth: []
      x-swagger-router-controller: Default
    options:
      operationId: apiFund_investmentsOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
  /api/logout:
    get:
      tags:
      - User Methods
      summary: Logout
      description: Logout investor user
      operationId: apiLogoutGET
      parameters:
      - name: custom-header
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Authorization
        in: header
        description: User session specific token for authorization
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
      security:
      - auth: []
      x-swagger-router-controller: UserMethods
    options:
      operationId: apiLogoutOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
  /api/user:
    get:
      operationId: apiUserGET
      parameters:
      - name: custom-header
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      security:
      - auth: []
      x-swagger-router-controller: Default
    options:
      operationId: apiUserOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
  /api/user-totals:
    get:
      operationId: apiUser_totalsGET
      parameters:
      - name: custom-header
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      security:
      - auth: []
      x-swagger-router-controller: Default
    options:
      operationId: apiUser_totalsOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
  /api/create-user:
    post:
      tags:
      - User Methods
      summary: Login
      description: Login investor user
      operationId: apiCreate_userPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        "400":
          description: 400 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400JsonResponse'
        "500":
          description: 500 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/500JsonResponse'
      x-swagger-router-controller: UserMethods
    options:
      operationId: apiCreate_userOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
  /api/user-messages:
    get:
      operationId: apiUser_messagesGET
      parameters:
      - name: custom-header
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      security:
      - auth: []
      x-swagger-router-controller: Default
    options:
      operationId: apiUser_messagesOPTIONS
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content: {}
      x-swagger-router-controller: Default
components:
  schemas:
    "400JsonResponse":
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: number
    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
        authToken:
          type: string
        user:
          type: object
      description: Successful login response object
      example:
        success: true
        authToken: authToken
        user: {}
    LogoutResponse:
      type: object
      properties:
        success:
          type: boolean
      description: Successful logout response object
      example:
        success: true
    "500JsonResponse":
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: number
    CreateUserRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        phone:
          type: string
        email:
          type: string
      description: Payload for creating user
    LoginRequest:
      type: object
      properties:
        password:
          type: string
        email:
          type: string
      description: Payload for login
  securitySchemes:
    auth:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: custom
